#!/usr/bin/env bash
# generate-index.sh — Auto-index generator for wiki-vault/
# Scans all concept nodes, generates per-pillar indexes and updates backlinks.
# Run from project root: bash scripts/generate-index.sh

set -euo pipefail

VAULT="wiki-vault"
CONCEPTS="$VAULT/concepts"
INDEXES="$VAULT/indexes"
INDEX_FILE="$VAULT/index.md"

# Ensure indexes/ directory exists (outside NODE_DIRS scan paths)
mkdir -p "$INDEXES"

# ─── Helper: extract frontmatter field value ──────────────────────────────────
get_field() {
  local file="$1" field="$2"
  awk "/^---/{f++} f==1 && /^${field}:/{gsub(/^${field}:[[:space:]]*/,\"\"); print; exit}" "$file"
}

# ─── Helper: extract frontmatter array items ──────────────────────────────────
get_array() {
  local file="$1" field="$2"
  awk "/^---/{f++} f==2{exit} f==1{
    if (/^${field}:/) { in_arr=1; next }
    if (in_arr && /^  - /) { gsub(/^  - /,\"\"); print; next }
    if (in_arr && /^[^ ]/) { in_arr=0 }
  }" "$file"
}

# ─── Step 1: Collect all concept nodes ───────────────────────────────────────
declare -A NODE_TITLE NODE_PILLAR NODE_SUMMARY
declare -a ALL_NODES

for pillar_dir in "$CONCEPTS"/*/; do
  pillar=$(basename "$pillar_dir")
  for node_file in "$pillar_dir"*.md; do
    [ -f "$node_file" ] || continue
    node_id=$(get_field "$node_file" "id")
    [ -z "$node_id" ] && continue
    title=$(get_field "$node_file" "title")
    summary=$(get_field "$node_file" "summary")
    NODE_TITLE[$node_id]="$title"
    NODE_PILLAR[$node_id]="$pillar"
    NODE_SUMMARY[$node_id]="$summary"
    ALL_NODES+=("$node_id")
  done
done

# ─── Step 2: Build reverse backlinks map ─────────────────────────────────────
# For each node, collect all nodes that reference it via:
#   (a) [[node-id]] wikilinks in body text
#   (b) related array in frontmatter
#   (c) prerequisites array in frontmatter

declare -A BACKLINKS  # BACKLINKS[target]="source1 source2 ..."

for pillar_dir in "$CONCEPTS"/*/; do
  pillar=$(basename "$pillar_dir")
  for node_file in "$pillar_dir"*.md; do
    [ -f "$node_file" ] || continue
    source_id=$(get_field "$node_file" "id")
    [ -z "$source_id" ] && continue

    # (a) wikilinks in body text — after the closing ---
    body_links=$(awk 'BEGIN{f=0} /^---/{f++; next} f>=2{print}' "$node_file" \
      | grep -oP '\[\[\K[^\]]+(?=\]\])' || true)

    # (b) related array
    related_ids=$(get_array "$node_file" "related")

    # (c) prerequisites array
    prereq_ids=$(get_array "$node_file" "prerequisites")

    for ref_id in $body_links $related_ids $prereq_ids; do
      ref_id="${ref_id//[[:space:]]/}"
      [ -z "$ref_id" ] && continue
      if [ -n "${BACKLINKS[$ref_id]+set}" ]; then
        # Only add if not already present
        if [[ " ${BACKLINKS[$ref_id]} " != *" $source_id "* ]]; then
          BACKLINKS[$ref_id]="${BACKLINKS[$ref_id]} $source_id"
        fi
      else
        BACKLINKS[$ref_id]="$source_id"
      fi
    done
  done
done

# ─── Step 3: Update ## Backlinks sections in concept nodes ───────────────────
for pillar_dir in "$CONCEPTS"/*/; do
  for node_file in "$pillar_dir"*.md; do
    [ -f "$node_file" ] || continue
    node_id=$(get_field "$node_file" "id")
    [ -z "$node_id" ] && continue

    refs="${BACKLINKS[$node_id]:-}"

    # Build backlinks content
    if [ -n "$refs" ]; then
      bl_content="## Backlinks"$'\n'
      for src in $refs; do
        bl_content+="- [[$src]]"$'\n'
      done
    else
      bl_content="## Backlinks"$'\n'
    fi

    # Replace existing ## Backlinks section (or append if missing)
    if grep -q "^## Backlinks" "$node_file"; then
      # Replace from ## Backlinks to EOF
      tmpfile=$(mktemp)
      awk '/^## Backlinks/{exit} {print}' "$node_file" > "$tmpfile"
      printf '%s' "$bl_content" >> "$tmpfile"
      mv "$tmpfile" "$node_file"
    else
      printf '\n%s' "$bl_content" >> "$node_file"
    fi
  done
done

# ─── Step 4: Generate per-pillar index files in wiki-vault/indexes/ ───────────
for pillar_dir in "$CONCEPTS"/*/; do
  pillar=$(basename "$pillar_dir")
  pillar_index="$INDEXES/${pillar}.md"

  {
    echo "# ${pillar^} Pillar Index"
    echo ""
    echo "Auto-generated by \`scripts/generate-index.sh\`. Do not edit manually."
    echo ""
    echo "## Nodes"
    echo ""

    for node_file in "$pillar_dir"*.md; do
      [ -f "$node_file" ] || continue
      node_id=$(get_field "$node_file" "id")
      [ -z "$node_id" ] && continue
      title="${NODE_TITLE[$node_id]}"
      summary="${NODE_SUMMARY[$node_id]}"
      prereqs=$(get_array "$node_file" "prerequisites")

      echo "### [[$node_id]]"
      echo ""
      echo "**Title:** $title"
      echo ""
      echo "**Summary:** $summary"
      echo ""
      if [ -n "$prereqs" ]; then
        echo "**Prerequisites:**"
        for p in $prereqs; do
          echo "- [[$p]]"
        done
      else
        echo "**Prerequisites:** none"
      fi
      echo ""
    done

    echo "## Prerequisite Graph"
    echo ""
    echo "\`\`\`"
    for node_file in "$pillar_dir"*.md; do
      [ -f "$node_file" ] || continue
      node_id=$(get_field "$node_file" "id")
      [ -z "$node_id" ] && continue
      prereqs=$(get_array "$node_file" "prerequisites")
      if [ -n "$prereqs" ]; then
        for p in $prereqs; do
          echo "$p → $node_id"
        done
      fi
    done
    echo "\`\`\`"
  } > "$pillar_index"

  echo "Generated: $pillar_index"
done

# ─── Step 5: Regenerate wiki-vault/index.md ───────────────────────────────────
{
  echo "# Wiki Vault Index"
  echo ""
  echo "This vault is the compiled knowledge base for the edu-runtime. It is managed by the Curriculum Agent workspace (\`workspaces/curriculum/\`)."
  echo ""
  echo "## Structure"
  echo ""
  echo "| Directory | Purpose |"
  echo "|-----------|---------|"
  echo "| \`sources/\` | Raw source material (docs, papers, transcripts). Never modified by agents. |"
  echo "| \`entities/\` | Wiki-compiled entity pages produced by \`wiki compile\`. |"
  echo "| \`concepts/agents/\` | Knowledge nodes for the Agents pillar. |"
  echo "| \`concepts/harnesses/\` | Knowledge nodes for the Harnesses pillar. |"
  echo "| \`concepts/openclaw/\` | Knowledge nodes for the OpenClaw pillar. |"
  echo "| \`templates/\` | Assessment templates (one per teachable node). |"
  echo "| \`syntheses/\` | Cross-concept synthesis pages. |"
  echo "| \`reports/\` | Generated coverage and lint reports. |"
  echo "| \`indexes/\` | Auto-generated per-pillar summary indexes. |"
  echo ""
  echo "## Runtime Consumption"
  echo ""
  echo "The \`ObsidianContentRepository\` in \`src/adapters/content/obsidian/\` reads from:"
  echo "- \`concepts/agents/\`, \`concepts/harnesses/\`, \`concepts/openclaw/\` — knowledge nodes"
  echo "- \`templates/\` — assessment templates"
  echo ""
  echo "## Concept Nodes"
  echo ""

  for pillar_dir in "$CONCEPTS"/*/; do
    pillar=$(basename "$pillar_dir")
    echo "### ${pillar^} Pillar — [[indexes/${pillar}|Index]]"
    echo ""
    for node_file in "$pillar_dir"*.md; do
      [ -f "$node_file" ] || continue
      node_id=$(get_field "$node_file" "id")
      [ -z "$node_id" ] && continue
      title="${NODE_TITLE[$node_id]}"
      echo "- [[$node_id|$title]]"
    done
    echo ""
  done

  echo "## Content Pipeline"
  echo ""
  echo "\`\`\`"
  echo "sources/ → wiki compile → entities/ + concepts/{pillar}/ → enrich-node → generate-template → wiki lint → generate-index → runtime-ready"
  echo "\`\`\`"
  echo ""
  echo "## Node Count"
  echo ""
  echo "Total nodes: ${#ALL_NODES[@]}"
  echo ""
  echo "See \`reports/\` for coverage statistics. See \`indexes/\` for per-pillar summaries."
} > "$INDEX_FILE"

echo "Generated: $INDEX_FILE"
echo "Done. ${#ALL_NODES[@]} nodes indexed."
